version: "3"

services:
  fpm-test:
    image: app-test
    container_name: api-test
    volumes:
      - ./:/var/www/html
      - ./storage:/var/www/html/storage
    depends_on:
      - db
      - redis
  web-test:
    image: web-test
    container_name: nginx-test
    depends_on:
      - fpm-test
    ports:
      - "80:80"
    volumes:
      - ./public:/var/www/html/public:ro
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/var/lib/redis
  db:
    image: mysql
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: recipe_ordering_system

volumes:
  data:
  redis-data:
